Repository awslabs/autonomous-driving-data-framework, pull requests merged in 2024-08, with the labels that each got.

#571 Run CI on all changed modules, not just the first one.
  .github/workflows/module-checks.yml
  modules/analysis/rosbag-image-pipeline-sfn/requirements-dev.txt
  modules/post-processing/yolo-object-detection/requirements.txt
  modules/post-processing/yolop-lane-detection/requirements.txt
Labels: workflows

#573 chore: update ros-image-demo manifests to use latest ecr module
  manifests/ros-image-demo/ros-image-demo-mwaa/docker-repository-modules.yaml
  manifests/ros-image-demo/ros-image-demo-sfn/docker-repository-modules.yaml
Labels: enhancement

#576 chore: update manifests to use latest idf modules
  docs/deployment_guide.md
  manifests/example-dev/core-modules.yaml
  manifests/example-dev/example-modules.yaml
  manifests/example-dev/optional-modules.yaml
  manifests/example-dev/replicator-modules.yaml
  requirements.txt
Labels: documentation, enhancement, dependencies
